# Generated by Django 5.0.3 on 2024-03-14 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='Downloads', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('events', models.ManyToManyField(related_name='events', to='bot.event', verbose_name='События')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Имя клиента')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='адрес')),
                ('date', models.DateField(blank=True, verbose_name='Дата доставки')),
                ('time', models.TimeField(blank=True, verbose_name='Время доставки')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bouquet')),
            ],
        ),
    ]
