# Generated by Django 5.0.3 on 2024-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_event', models.CharField(max_length=200, null=True)),
                ('click_price', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
