# Generated by Django 5.0.3 on 2024-03-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.bouquet'),
        ),
    ]
