# Generated by Django 5.0.3 on 2024-03-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_order_bouquet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Время доставки'),
        ),
    ]
